### PR TITLE
Fix context manager - return the client upon enter

### PR DESCRIPTION
**Pull request by bozhodimitrov**
The magic method that should return self is the __enter__ one and not the __exit__ one.
Cheers and thanks for creating this project!

### CODE REVIEW

**Comment by JohnDoee** [comment]
Thanks for fixing it, it'll be out with 1.8.1 which I release when tests are done.

**Comment by bozhodimitrov** [comment]
Can i backport one more thing from synchronous deluge, before you release?
It is the automatic connection to a local Deluge instance.

```python
client = DelugeRPCClient() # don't pass username/password
client.connect() # connects to your local instance with the username and password created by Deluge itself
```

**Comment by JohnDoee** [comment]
Sure

**Comment by JohnDoee** [comment]
I'm not sure I want that directly in the library but would be happy to have it as an example. To me it feels like directly integrating it would increase edge-cases and complexity of maintaining it.

You can see the basic logic for Linux here https://github.com/JohnDoee/autotorrent/blob/develop/autotorrent/clients/deluge.py#L57-L101 which works much the same way as Deluge GTK.

**Comment by bozhodimitrov** [comment]
Yea, I know exactly what you mean. I also hate maintaining messy code.
This is why I am trying to make it more readable and error prune at the moment.

**Comment by bozhodimitrov** [comment]
@JohnDoee what do you think of this change: [Add automatic login for local Deluge instances](https://github.com/int3l/deluge-client/commit/3a3c0ce607364f52c99351aab68a65c875335a4b)

Sorry for hijacking this PR with offtopic, but I don't want to spam you with new Issues/PRs without a reason.

**Pull request merged**
